spring:
  cloud:
    # Spring Cloud Stream 配置项，对应 BindingServiceProperties 类
    stream:
      # Binding 配置项，对应 BindingProperties Map
      bindings:
        shuchu:
          destination: test-topic # 目的地。这里使用 RocketMQ Topic
          content-type: application/json # 内容格式。这里使用 JSON
        shuru:
          destination: test-topic # 目的地。这里使用 RocketMQ Topic
          content-type: application/json # 内容格式。这里使用 JSON
          group: test-group
      # Spring Cloud Stream RocketMQ 配置项
      rocketmq:
        # RocketMQ Namesrv 地址
        binder:
          name-server: 123.57.34.92:9876
        # RocketMQ 自定义 Binding 配置项，对应 RocketMQBindingProperties Map
        bindings:
          shuru:
            # RocketMQ Producer 配置项，对应 RocketMQProducerProperties 类
            consumer:
              group: test # 生产者分组
              sync: true # 是否同步发送消息，默认为 false 异步。

server:
  port: 4545
